version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
    - APP_CONFIG_PATH=/data/config/config.json
    - USE_EMBEDDED_DB
    volumes:
    - ../trackman-config:/data/config
    external_links:
    - postgres
    depends_on:
    - redis
  nginx:
    image: meroje/alpine-nchan:1.1.8
    ports:
    - "9090:80"
    expose:
    - "9090"
    depends_on:
    - app
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./trackman/static:/srv/http/static
  redis:
    image: redis:4-alpine
    expose:
     - "6379"
