version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - "9090:8080"
    expose:
    - "8080"
    environment:
    - APP_CONFIG_PATH=/data/config/config.json
    - USE_EMBEDDED_DB
    volumes:
    - ../trackman-config:/data/config
    external_links:
    - postgres
    depends_on:
    - redis
    - nchan
  nchan:
    image: meroje/alpine-nchan:1.1.8
    ports:
    - "9075:80"
    expose:
    - "80"
    volumes:
    - ./nchan/nginx.conf:/etc/nginx/nginx.conf
    - ./nchan/conf.d:/etc/nginx/conf.d
  redis:
    image: redis:4-alpine
    expose:
     - "6379"
